# Это основной конфигурационный файл для вашего приложения Spring Boot.

# Настройки HTTP-сервера
server:
  port: 8080 # Порт, на котором будет работать приложение (по умолчанию 8080)
  tomcat:
    relaxed-query-chars: "|" # Разрешает использование символа '|' в URL-адресах запросов

# Настройки Actuator (для мониторинга и управления приложением)
management:
  endpoints:
    enabled-by-default: false # По умолчанию все конечные точки отключены
    web:
      exposure:
        include: 'health' # Включить только конечную точку '/actuator/health'
        # Можно добавить 'info,prometheus,metrics' или '*' для всех
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - readinessState
    prometheus: # Включить конечную точку Prometheus для метрик
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Основные настройки Spring Framework
spring:
  main:
    allow-circular-references: true # Разрешает круговые ссылки между компонентами Spring
  flyway: # Инструмент для управления версиями базы данных
    enabled: false # Отключен по умолчанию
    baselineOnMigrate: true
    fail-on-missing-locations: false
  datasource: # Настройки подключения к базе данных
    url: jdbc:postgresql://localhost:5432/hapi # URL подключения к PostgreSQL
    username: postgres # Имя пользователя базы данных
    password: 1234 # Пароль базы данных
    driverClassName: org.postgresql.Driver # Класс драйвера JDBC
    max-active: 15 # Максимальное количество активных подключений в пуле (устарело, лучше использовать hikari.maximum-pool-size)
    hikari: # Настройки пула подключений HikariCP (используется по умолчанию в Spring Boot)
      maximum-pool-size: 10 # Максимальное количество подключений в пуле HikariCP
      auto-commit: false
  jpa: # Настройки JPA (Java Persistence API) и Hibernate
    # Если вы хотите, чтобы Hibernate автоматически создавал/обновлял схему базы данных,
    # раскомментируйте одну из следующих строк:
    hibernate.ddl-auto: update # Обновляет схему БД (осторожно в продакшене!)
    #hibernate.ddl-auto: create-drop # Создает схему при запуске и удаляет при остановке (для разработки)
    # hibernate.ddl-auto: validate # Проверяет, что схема БД соответствует сущностям (хорошо для продакшена)
    show-sql: false # Не выводить SQL-запросы в консоль
    properties: # Дополнительные свойства Hibernate
      hibernate.format_sql: false # Не форматировать SQL-запросы в логах
      hibernate.show_sql: false # Не выводить SQL-запросы в логах (дублирует show-sql выше)
      hibernate.search.enabled: false # Отключить Hibernate Search (если не используется)
      # Диалект Hibernate для PostgreSQL. Эта строка должна быть ОДНА И НЕ ЗАКОММЕНТИРОВАНА.
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      # Дополнительные рекомендуемые свойства Hibernate для производительности и корректной работы
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.integration.envers.enabled: true
    open-in-view: false # Отключить паттерн Open Session In View (рекомендуется для веб-приложений)

# Настройки HAPI FHIR (специфичные для сервера HAPI FHIR JPA)
hapi:
  fhir:
    cr: # Clinical Reasoning Module
      enabled: false
      caregaps:
        reporter: "default"
        section_author: "default"
      cql:
        use_embedded_libraries: true
        compiler:
          error_level: Info
          signature_level: All
          enable_annotations: true
          enable_locators: true
          enable_results_type: true
          enable_detailed_errors: true
        runtime:
          debug_logging_enabled: false
        terminology:
          valueset_preexpansion_mode: REQUIRE
          valueset_expansion_mode: PERFORM_NAIVE_EXPANSION
          valueset_membership_mode: USE_EXPANSION
          code_lookup_mode: USE_VALIDATE_CODE_OPERATION
        data:
          search_parameter_mode: USE_SEARCH_PARAMETERS
          terminology_parameter_mode: FILTER_IN_MEMORY
          profile_mode: DECLARED

    cdshooks: # CDS Hooks Server
      enabled: false
      clientIdHeaderName: client_id

    openapi_enabled: true # Включить поддержку OpenAPI/Swagger UI
    fhir_version: R4 # Версия FHIR (DSTU2, DSTU3, R4, R5)
    ig_runtime_upload_enabled: false # Разрешить загрузку Implementation Guides во время выполнения

    narrative_enabled: false # Отключить генерацию нарративов
    mdm_enabled: false # Отключить Master Data Management (MDM)
    mdm_rules_json_location: "mdm-rules.json"

    logical_urls: # Разрешенные логические URL-адреса для терминологии
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*

    cors: # Настройки CORS (Cross-Origin Resource Sharing)
      allow_Credentials: true
      allowed_origin:
        - '*' # Разрешить запросы со всех источников (осторожно в продакшене!)

    search-coord-core-pool-size: 20 # Размер пула потоков для координатора поиска
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200

    search_prefetch_thresholds: 13,503,2003,-1 # Пороги предварительной выборки результатов поиска

    #custom-bean-packages: ca.uhn.fhir.jpa.starter.custom # Можно использовать для сканирования пользовательских бинов Spring (через @ComponentScan)
    custom-interceptor-classes: ca.uhn.fhir.jpa.starter.custom.CustomFhirHook # Пользовательские классы интерцепторов

    inline_resource_storage_below_size: 4000 # Размер в байтах для хранения ресурсов inline в БД

    # Если вы хотите включить расширенное индексирование Lucene/Elasticsearch, раскомментируйте соответствующую секцию
    advanced_lucene_indexing: false
    search_index_full_text_enabled: false

    bulk_export_enabled: false # Отключить возможность массового экспорта FHIR
    bulk_import_enabled: false # Отключить возможность массового импорта FHIR

    tester: # Настройки FHIR Tester UI
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4